### ISSUE TITLE
KEyError: 'productinfo'

### ISSUE THREAD

**Issue by SebastianLischer** [yasserqureshi1/Sneaker-Monitors#106]
Exception found: Traceback (most recent call last):
  File "c:\Users\z00475vu\Documents\GitHub\Cook-Group-Monitors\Finished_Monitors\SNKRS-test.py", line 189, in monitor
    for j in item['productInfo']:
KeyError: 'productInfo'

just getting this error all the time and realy dont know how to fix it
im running the original programm direct from ur github

**Comment by yasserqureshi1** [comment]
I had a look and i realised that I’m printing these exceptions. This key error occurs because on the SNKRS app and website there are some posts that are sneakers you can buy as well as other posts like videos and pictures and it tries to filter them out. However the error that you see isn’t an issue - it just prints it out. I’ll get rid of this in the next update as it can be annoying and misinterpreted
